INSERT INTO `m_permission`
(`grouping`,`code`,`entity_name`,`action_name`,`can_maker_checker`)
VALUES
('portfolio', 'READ_CLIENTADDRESS', 'CLIENTADDRESS', 'READ', 0),
('portfolio', 'CREATE_CLIENTADDRESS', 'CLIENTADDRESS', 'CREATE', 0),
('portfolio', 'CREATE_CLIENTADDRESS_CHECKER', 'CLIENTADDRESS', 'CREATE_CHECKER', 0),
('portfolio', 'UPDATE_CLIENTADDRESS', 'CLIENTADDRESS', 'UPDATE', 0),
('portfolio', 'UPDATE_CLIENTADDRESS_CHECKER', 'CLIENTADDRESS', 'UPDATE_CHECKER', 0),
('portfolio', 'DELETE_CLIENTADDRESS', 'CLIENTADDRESS', 'DELETE', 0),
('portfolio', 'DELETE_CLIENTADDRESS_CHECKER', 'CLIENTADDRESS', 'DELETE_CHECKER', 0);
